baseURL = "https://isdotdot.github.io/blog/"
languageCode = "en-us"
title = "Why Things Happen"
paginate = 10

[params]
  siteDescription = "Friendly, simple explanations for everyday 'why does...?' questions."
